"""add_tier2_tables

Revision ID: 2bbed0d238fc
Revises: 001
Create Date: 2026-06-18 03:29:35.312372+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bbed0d238fc'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.Enum('H24', 'H48', 'H7', 'H14', 'H28', 'H90', name='log_type_enum'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr_percentage', sa.Float(), nullable=False),
    sa.Column('avd_seconds', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('pulled_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_pulled', 'analytics_logs', ['channel_id', 'pulled_at'], unique=False)
    op.create_index('idx_video_type', 'analytics_logs', ['youtube_video_id', 'log_type'], unique=False)
    op.create_table('thumbnail_styles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('style_name', sa.String(length=100), nullable=False),
    sa.Column('template_path', sa.String(length=500), nullable=True),
    sa.Column('avg_ctr', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeslot_performance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('avg_views_48h', sa.Float(), nullable=False),
    sa.Column('avg_ctr', sa.Float(), nullable=False),
    sa.Column('avg_avd_seconds', sa.Integer(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'day_of_week', 'hour_of_day', name='uq_channel_slot')
    )
    op.create_index('idx_channel_confidence', 'timeslot_performance', ['channel_id', 'confidence_score'], unique=False)
    op.create_table('video_evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=50), nullable=False),
    sa.Column('eval_stage', sa.Enum('H24', 'H48', 'H7', 'H14', 'H28', 'H90', name='log_type_enum'), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('ctr_percentage', sa.Float(), nullable=False),
    sa.Column('avd_seconds', sa.Integer(), nullable=False),
    sa.Column('baseline_ctr', sa.Float(), nullable=True),
    sa.Column('baseline_avd', sa.Float(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('diagnosis_summary', sa.Text(), nullable=True),
    sa.Column('hermes_confidence', sa.Float(), nullable=True),
    sa.Column('recommended_action', sa.Enum('KEEP', 'CHANGE_THUMBNAIL', 'CHANGE_TITLE', 'CHANGE_DESCRIPTION', 'CHANGE_MULTIPLE', 'CHECK_CONTENT', 'WAIT_MORE_DATA', name='recommended_action_enum'), nullable=True),
    sa.Column('eval_status', sa.Enum('PENDING', 'ANALYZED', 'ACTION_REQUIRED', 'ACTION_TAKEN', 'CLOSED', name='eval_status_enum'), nullable=False),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['upload_queue.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_status', 'video_evaluations', ['eval_status', 'created_at'], unique=False)
    op.create_index('idx_queue_stage', 'video_evaluations', ['queue_id', 'eval_stage'], unique=False)
    op.create_table('video_tracklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('track_position', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=255), nullable=False),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['upload_queue.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_queue_tracks', 'video_tracklist', ['queue_id'], unique=False)
    op.create_table('evaluation_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('option_type', sa.Enum('TITLE', 'DESCRIPTION', 'THUMBNAIL', name='option_type_enum'), nullable=False),
    sa.Column('option_value', sa.Text(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['video_evaluations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_type', 'evaluation_options', ['evaluation_id', 'option_type'], unique=False)
    op.alter_column('channel_credentials', 'key_version',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('channel_credentials', 'auth_status',
               existing_type=mysql.ENUM('VALID', 'NEEDS_REAUTH', 'REVOKED'),
               server_default=None,
               nullable=False)
    op.alter_column('channel_credentials', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('channel_credentials', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('channels', 'gcp_project_id',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               nullable=False)
    op.alter_column('channels', 'trust_level',
               existing_type=mysql.ENUM('NEW', 'TRUSTED'),
               server_default=None,
               nullable=False)
    op.alter_column('channels', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=False)
    op.alter_column('channels', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('channels', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('file_checksums', 'detected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('gcp_quota_tracker', 'units_used_today',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('gcp_quota_tracker', 'units_limit',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('gcp_quota_tracker', 'version',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('gcp_quota_tracker', 'last_updated',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('metadata_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('system_audit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('system_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('upload_attempts', 'started_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('upload_attempts', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=False)
    op.alter_column('upload_queue', 'is_human_override',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               nullable=False)
    op.alter_column('upload_queue', 'status',
               existing_type=mysql.ENUM('PENDING', 'METADATA_READY', 'AWAITING_APPROVAL', 'SCHEDULED', 'UPLOADING', 'PRIVATE_UPLOADED', 'THUMBNAIL_ATTACHED', 'SCHEDULED_PUBLIC', 'DONE', 'THUMBNAIL_FAILED', 'FAILED_PERMANENT', 'PAUSED', 'PAUSED_EXTERNAL', 'QUOTA_EXHAUSTED', 'NEEDS_REAUTH'),
               server_default=None,
               nullable=False)
    op.alter_column('upload_queue', 'retry_count',
               existing_type=mysql.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('upload_queue', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('upload_queue', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('upload_state_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('video_tags', 'source',
               existing_type=mysql.ENUM('AI', 'HUMAN'),
               server_default=None,
               nullable=False)
    op.alter_column('video_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_tags', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('video_tags', 'source',
               existing_type=mysql.ENUM('AI', 'HUMAN'),
               server_default=sa.text("'AI'"),
               nullable=True)
    op.alter_column('upload_state_history', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('upload_queue', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('upload_queue', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('upload_queue', 'retry_count',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)
    op.alter_column('upload_queue', 'status',
               existing_type=mysql.ENUM('PENDING', 'METADATA_READY', 'AWAITING_APPROVAL', 'SCHEDULED', 'UPLOADING', 'PRIVATE_UPLOADED', 'THUMBNAIL_ATTACHED', 'SCHEDULED_PUBLIC', 'DONE', 'THUMBNAIL_FAILED', 'FAILED_PERMANENT', 'PAUSED', 'PAUSED_EXTERNAL', 'QUOTA_EXHAUSTED', 'NEEDS_REAUTH'),
               server_default=sa.text("'PENDING'"),
               nullable=True)
    op.alter_column('upload_queue', 'is_human_override',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               nullable=True)
    op.alter_column('upload_attempts', 'success',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               nullable=True)
    op.alter_column('upload_attempts', 'started_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('system_config', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('system_audit_log', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('metadata_history', 'changed_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('gcp_quota_tracker', 'last_updated',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('gcp_quota_tracker', 'version',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               nullable=True)
    op.alter_column('gcp_quota_tracker', 'units_limit',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'10000'"),
               nullable=True)
    op.alter_column('gcp_quota_tracker', 'units_used_today',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               nullable=True)
    op.alter_column('file_checksums', 'detected_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('channels', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('channels', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('channels', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'1'"),
               nullable=True)
    op.alter_column('channels', 'trust_level',
               existing_type=mysql.ENUM('NEW', 'TRUSTED'),
               server_default=sa.text("'NEW'"),
               nullable=True)
    op.alter_column('channels', 'gcp_project_id',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'project_default'"),
               nullable=True)
    op.alter_column('channel_credentials', 'updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('channel_credentials', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               nullable=True)
    op.alter_column('channel_credentials', 'auth_status',
               existing_type=mysql.ENUM('VALID', 'NEEDS_REAUTH', 'REVOKED'),
               server_default=sa.text("'VALID'"),
               nullable=True)
    op.alter_column('channel_credentials', 'key_version',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'1'"),
               nullable=True)
    op.drop_index('idx_eval_type', table_name='evaluation_options')
    op.drop_table('evaluation_options')
    op.drop_index('idx_queue_tracks', table_name='video_tracklist')
    op.drop_table('video_tracklist')
    op.drop_index('idx_queue_stage', table_name='video_evaluations')
    op.drop_index('idx_eval_status', table_name='video_evaluations')
    op.drop_table('video_evaluations')
    op.drop_index('idx_channel_confidence', table_name='timeslot_performance')
    op.drop_table('timeslot_performance')
    op.drop_table('thumbnail_styles')
    op.drop_index('idx_video_type', table_name='analytics_logs')
    op.drop_index('idx_channel_pulled', table_name='analytics_logs')
    op.drop_table('analytics_logs')
    # ### end Alembic commands ###
